services:
  storage:
    image: minio/minio:RELEASE.2024-08-17T01-24-54Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: "@Password123!"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - storage:/data
    networks:
      - go_networks
    restart: unless-stopped

volumes:
  storage:

networks:
  go_networks:
